import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Navbar } from '../organisms/Navbar';
import { LoginForm } from '../organisms/LoginForm';

const Login: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Indigo League</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      {/* <main className={styles.main}> */}
        <h1 className={styles.title}>
          Login
        </h1>

        <LoginForm/>
      {/* </main> */}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developed by Bthornton
        </a>
      </footer>
    </div>
  )
}

export default Login
