import React from "react";
import Head from 'next/head';
import { Navbar } from "./Navbar";
import styles from '../styles/Home.module.css'
import { Box, Container } from '@mui/material';

export const Layout = ({ ...props }) => {
  return (
    <Container maxWidth="xl">
      <Head>
        <title>Indigo League</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar/>

      <Box sx={{ margin: '8rem 50px' }}>
        {props.children}
      </Box>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developed by Bthornton
        </a>
      </footer>
    </Container>
  )
};
